// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwnNRmOcqcMwSpiyCmtuw5lS66-ZZpPU',
    appId: '1:343877425513:web:3d21d5b9dac8ab6c2085f8',
    messagingSenderId: '343877425513',
    projectId: 'zoopernova-c3a89',
    authDomain: 'zoopernova-c3a89.firebaseapp.com',
    storageBucket: 'zoopernova-c3a89.firebasestorage.app',
    measurementId: 'G-33YD3B3BYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvgniLzO3KesyhJ5kvknedwwk7uAgewXY',
    appId: '1:343877425513:android:0d51e8c6e17c00362085f8',
    messagingSenderId: '343877425513',
    projectId: 'zoopernova-c3a89',
    storageBucket: 'zoopernova-c3a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudgBAYIZSLbugJSJ6lVsAdRC3uLEM-kY',
    appId: '1:343877425513:ios:2e4f369dfe4431772085f8',
    messagingSenderId: '343877425513',
    projectId: 'zoopernova-c3a89',
    storageBucket: 'zoopernova-c3a89.firebasestorage.app',
    iosBundleId: 'com.example.zoopernovaZooSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudgBAYIZSLbugJSJ6lVsAdRC3uLEM-kY',
    appId: '1:343877425513:ios:2e4f369dfe4431772085f8',
    messagingSenderId: '343877425513',
    projectId: 'zoopernova-c3a89',
    storageBucket: 'zoopernova-c3a89.firebasestorage.app',
    iosBundleId: 'com.example.zoopernovaZooSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUwnNRmOcqcMwSpiyCmtuw5lS66-ZZpPU',
    appId: '1:343877425513:web:a88ecb1b783681902085f8',
    messagingSenderId: '343877425513',
    projectId: 'zoopernova-c3a89',
    authDomain: 'zoopernova-c3a89.firebaseapp.com',
    storageBucket: 'zoopernova-c3a89.firebasestorage.app',
    measurementId: 'G-XR9HE6R2DH',
  );
}
